### PR TITLE
Migrate dummy app to pods

### PR DESCRIPTION
**Pull request by mmun**
@ef4 What do you think of using pods in the dummy app? I was already start to feel the pain of flipping back and forth between different folders and the documentation site is only going to get larger :)

### CODE REVIEW

**Comment by mmun** [comment]
The errors in beta/canary look unrelated to this PR:

```
Error: Use of @ember/MapWithDefault is deprecated. Please use native `Map` instead
```

**Comment by ef4** [comment]
I am disinclined to switch to pods when it’s already possible to switch to module unification instead. 

But I’m happy to switch to MU.

**Comment by mmun** [comment]
As far as I can tell, MU requires a feature in ember-source canary so we wouldn't be able to test against non-canary builds. I'll look into it.

**Comment by ef4** [comment]
I think the proposed solution for addons to support both classic and MU apps is having multiple dummy apps. I would be fine with that -- the docs site can be MU, while we also maintain test coverage for classic in another dummy app.

**Pull request closed without merging**
