### PR TITLE
Fix scheduler in 3.6

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
@cibernox any chance you can address the test failures here? We're getting caught by this error now too and would love to get it resolved.

If you don't have time, I can try to get the tests passing if that helps get this PR merged.

**Comment by cibernox** [comment]
It has been blocked by this for over a week: https://github.com/ebryn/ember-component-css/pull/308

Once merged it will be fixesm

**Comment by alexlafroscia** [comment]
I see -- thanks for the context!

**Comment by ef4** [comment]
Thanks again.

I thought I was going mad because just as I had everything working, we got hit by a babel regression that released just 8 hours ago. 😛

**Pull request merged**
