### PR TITLE
Fix template lint issues / block-indentation

### PR DESCRIPTION
**Pull request by esbanarango**
This PR fixes template lint issues related to `block-indentation`.
partial fix for #52

### CODE REVIEW

**Comment by ef4** [comment]
(I'm in the middle of fixing the travis build, so if you see failures it is probably not your fault.)

**Comment by esbanarango** [comment]
There was actually a legit lint error there and a conflict with `yarn.lock`. I just fixed it.

**Comment by esbanarango** [comment]
Back to green 🤝

**Comment by ef4** [comment]
Thanks!

**Pull request merged**
