### PR TITLE
Update the Sprites page

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by samselikoff** [comment]
Looks like master is broken

**Comment by cibernox** [comment]
@samselikoff it is because of a few addons, addon-docs included. Can you check a PR o made this weekend?

**Comment by samselikoff** [comment]
@cibernox yessir, looking now. Thank you!

**Comment by samselikoff** [comment]
@cibernox fwiw we published 0.6.2 https://github.com/ember-learn/ember-cli-addon-docs/releases/tag/v0.6.2

**Comment by ef4** [comment]
Thanks @samselikoff!

**Pull request merged**
