### PR TITLE
Docs improvements

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by samselikoff** [comment]
I've reached a pretty good point with the homepage! Figured we could get this merged at this point.

You can see the build here: https://ember-animation.github.io/ember-animated/versions/docs-improvements/

There's lots more work to do to the documentation but I'm limited on time so I will contribute in the future as I can in smaller chunks.

This PR does a few things:

- new docs homepage
- pods-ifies the dummy app 
- uses `for...of` in all API doc examples (but not guides, still more work to do there)
- upgrades AddonDocs
- hides private modules from the docs

**Comment by samselikoff** [comment]
tests pass, think this is ready for review!

**Comment by ef4** [comment]
Thanks, this is all looking fantastic.

**Comment by ef4** [comment]
Feel free to cut a release when you're ready so this become the default deployed homepage.

**Comment by samselikoff** [comment]
@ef4 sweet. We should set up Travis to release new tags created from github. ([example](https://github.com/samselikoff/ember-cli-mirage/blob/master/.travis.yml#L60))

**Comment by samselikoff** [comment]
@ef4 Travis can now release to npm, so all we have to do is increment the version in `package.json`, then go to Releases page and draft a new release with the same name as that version, and Travis will take care of the rest.

It's nice because cutting a release can all be done from the GitHub ui.

**Comment by samselikoff** [comment]
In addition to not having to add new collaborators to npm

**Pull request merged**
