### PR TITLE
Allow multiple beacons with the same name

### PR DESCRIPTION
**Pull request by mattmarcum**
This addresses https://github.com/ember-animation/ember-animated/issues/225

First commit I added a failing test that just had a beacon and two animated-ifs.  That test fails like the bug describes.

After diving into the code a bit I feel that this assertion was put here in error.  As the added test shows, when multiple animated components are present the beacon will [add itself](https://github.com/ember-animation/ember-animated/blob/master/addon/src/components/animated-beacon.ts#L121) to the -ea-motion service once per new animation. 
 This is because the beacons are [listening to all animations](https://github.com/ember-animation/ember-animated/blob/master/addon/src/components/animated-beacon.ts#L78).  The original authors didn't cover the case when multiple animations would start in the same cycle, i.e. when more than one animated component gets rendered on the page.

I added a `hasBeacon` method so that the Beacon component can return early if it's already added itself to the service.  

The problem the original author tried to help with, warning when devs add two similar named beacons, is tough to crack with this implementation.  I think its better to just fix this error and fore-go the warning.  

One thing to note, the original error didn't really impede animations.  Throwing an error would effective cause the `addBeacon` task to exit early and the sprite never got updated.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@mattmarcum could you please fix lint?

This looks good to me, but I'd like @ef4 to chime in to confirm this is the right fix.

**Review by SergeAstapov — CHANGES_REQUESTED** [review]
Let's make ESLint happy

**Review by ef4 — APPROVED** [review]
Thanks, this seems good to me. Once Serge’s comments are addressed this is good to go.

**Comment by mattmarcum** [comment]
pushed up lint fixes

**Review by SergeAstapov — APPROVED** [review]

**Comment by SergeAstapov** [comment]
@mattmarcum this is now published as `ember-animated@1.0.2-unstable.6497bef` could you please give it a try?

**Comment by mattmarcum** [comment]
I tried locally and can confirm the erros no longer flood the consol.

**Pull request merged**
