### PR TITLE
[WIP] Sprite JSDoc

### PR DESCRIPTION
**Pull request by Oreoz**
Currently working on describing the Sprite API using JSDoc -- relates to #15.

@ef4 Do you think describing the behaviour of this API using JSDoc which will then be automatically processed into the API Reference section of the docs website by Addon Docs to be adequate? I'm simply asking because when I initially created the skeleton I added a dedicated Sprite API page in there and I think it might be redundant.

### CODE REVIEW

**Comment by ef4** [comment]
I think we will probably want both API reference and a more narrative/tutorial/guides section, so this is fine.

I haven't looked yet into how ember-cli-addon-docs supports the distinction between public & private API, but that's an important area to keep in mind. I don't want to overwhelm readers with internal methods (for example, some of the things in this PR like bounds.js are really only internal for the present). 

Of course it's also valuable to document the internal methods, and it would be fantastic if we can offer a checkbox that enables "internals" docs for advanced readers who know what they're looking for.

**Comment by Oreoz** [comment]
So if I understand correctly; you'd want to have the public API References available in the sidebar and the user could opt-in in using a checkbox / keyboard shortcut in order to see the private stuff?

As far as `ember-cli-addon-docs` goes it doesn't look like they have private vs public opt-in already available but that could easily be implemented (we'd of course have to validate they would entertain a PR for this feature) since the data that's in the store does contain visibility information that's parsed from the JSDoc decorators (`@private` and `@public`).

**Comment by ef4** [comment]
Right. The Ember API docs do something similar here:

screen shot 2018-03-17 at 11 12 39 am

Although in that case I don't think the checkbox affects global navigation, which would be nice.

**Comment by tim-evans** [comment]
@Oreoz I would chat with them; the team seems very friendly!

I'm already having a pretty good discussion over here :) https://github.com/ember-learn/ember-cli-addon-docs/issues/115

**Comment by Oreoz** [comment]
@tim-evans Just haven't gone around to actually talking with them -- but I met Sam at Emberconf and he's indeed quite friendly, just like most of the community ;)

**Comment by ef4** [comment]
I merged your progress so far, since there's no downside to having incomplete docs in master. Keep up the great work.

**Pull request merged**
